version: "3"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/ssl/certs:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
